// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: apiServerGrpc.proto

package apiServerGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HolidayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day   string `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Month string `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	Year  string `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
}

func (x *HolidayRequest) Reset() {
	*x = HolidayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiServerGrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolidayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolidayRequest) ProtoMessage() {}

func (x *HolidayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiServerGrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolidayRequest.ProtoReflect.Descriptor instead.
func (*HolidayRequest) Descriptor() ([]byte, []int) {
	return file_apiServerGrpc_proto_rawDescGZIP(), []int{0}
}

func (x *HolidayRequest) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *HolidayRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *HolidayRequest) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

// The response message containing the greetings
type Holiday struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Holiday) Reset() {
	*x = Holiday{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiServerGrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Holiday) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Holiday) ProtoMessage() {}

func (x *Holiday) ProtoReflect() protoreflect.Message {
	mi := &file_apiServerGrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Holiday.ProtoReflect.Descriptor instead.
func (*Holiday) Descriptor() ([]byte, []int) {
	return file_apiServerGrpc_proto_rawDescGZIP(), []int{1}
}

func (x *Holiday) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Holiday) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_apiServerGrpc_proto protoreflect.FileDescriptor

var file_apiServerGrpc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x47, 0x72, 0x70, 0x63, 0x22, 0x4c, 0x0a, 0x0e, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x12,
	0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x22, 0x3f, 0x0a, 0x07, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x32, 0x54, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x49,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79,
	0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63,
	0x2e, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x61, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x44, 0x61, 0x6e,
	0x69, 0x61, 0x6c, 0x2d, 0x4d, 0x6f, 0x76, 0x61, 0x68, 0x65, 0x64, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apiServerGrpc_proto_rawDescOnce sync.Once
	file_apiServerGrpc_proto_rawDescData = file_apiServerGrpc_proto_rawDesc
)

func file_apiServerGrpc_proto_rawDescGZIP() []byte {
	file_apiServerGrpc_proto_rawDescOnce.Do(func() {
		file_apiServerGrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_apiServerGrpc_proto_rawDescData)
	})
	return file_apiServerGrpc_proto_rawDescData
}

var file_apiServerGrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apiServerGrpc_proto_goTypes = []interface{}{
	(*HolidayRequest)(nil), // 0: apiServerGrpc.holidayRequest
	(*Holiday)(nil),        // 1: apiServerGrpc.holiday
}
var file_apiServerGrpc_proto_depIdxs = []int32{
	0, // 0: apiServerGrpc.Greeter.RequestHoliday:input_type -> apiServerGrpc.holidayRequest
	1, // 1: apiServerGrpc.Greeter.RequestHoliday:output_type -> apiServerGrpc.holiday
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apiServerGrpc_proto_init() }
func file_apiServerGrpc_proto_init() {
	if File_apiServerGrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apiServerGrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HolidayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apiServerGrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Holiday); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apiServerGrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiServerGrpc_proto_goTypes,
		DependencyIndexes: file_apiServerGrpc_proto_depIdxs,
		MessageInfos:      file_apiServerGrpc_proto_msgTypes,
	}.Build()
	File_apiServerGrpc_proto = out.File
	file_apiServerGrpc_proto_rawDesc = nil
	file_apiServerGrpc_proto_goTypes = nil
	file_apiServerGrpc_proto_depIdxs = nil
}
